build:
	cd ../Maze && mvn package -Dpackage.jar.main.class=harness.RefereeHarness -Dpackage.jar.name=RefereeHarness -DskipTests
	cd ../Maze && mvn package -Dpackage.jar.main.class=harness.ObserverHarness -Dpackage.jar.name=ObserverHarness -DskipTests
